config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mdapp.urls', 'mdapp'), namespace='mdapp')),
    path("accounts/", include("accounts.urls")),
]

mdapp/urls.py
from django.urls import path 
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'mdapp'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', login_required(views.List.as_view()), name='index'),
    path('create/', login_required(views.CreateFile.as_view()), name='create'),
    path('files/<str:pk>', login_required(views.Detail.as_view()), name='ditail'),
    path('files/<str:pk>/update', login_required(views.UpdateFile.as_view()), name='update'),
    path('files/<str:pk>/delete', login_required(views.Delet.as_view()), name='delete'),
    path('files/<str:pk>/pdf', login_required(views.get_pdf_bytedeta), name='pdf'),
    path('files/<str:pk>/img', login_required(views.generate_thumbnail), name='img'),
    path('files/<str:pk>/share', login_required(views.share), name='share'),
    path('img/<str:filename>', login_required(views.get_img), name='get_img'),
    path('shared/', login_required(views.Shared.as_view()), name='shared'),
    path('shared/<str:pk>/create', login_required(views.CreateShared.as_view()), name="create_shared")
]

mdapp/models.py
from django.db import models
import uuid
from django.utils import timezone

def generate_id(length=8):
    import string, random
    chars = string.ascii_letters + string.digits
    while True:
        new_id = ''.join(random.choices(chars, k=length))
        if not Mdfile.objects.filter(id=new_id).exists():
            return new_id

class Share(models.Model):
    id = models.CharField(
        primary_key=True,
        max_length=20,
        unique=True,
        default=generate_id,
        editable=False
    )
    file = models.ForeignKey(
        "mdapp.Mdfile",
        on_delete=models.CASCADE
    )
    to_user = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)

# Create your models here.
class Mdfile(models.Model):
    class Meta:
        db_table = 'mdfiles'

    id = models.CharField(
        primary_key=True,
        max_length=20,
        unique=True,
        default=generate_id,
        editable=False
    )
    title = models.CharField(verbose_name='ファイル名', max_length=100)
    base_text = models.TextField(verbose_name='文書データ')
    html_text = models.TextField(verbose_name='htmlデータ')
    url = models.CharField(verbose_name='pdfurl', max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now_add=True)
    user = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE
    )

    # 同じユーザで同じタイトルを許さない
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'title'], name='unique_title_per_user')
        ]

    def __str__(self):
        return super().__str__()

mdapp/forms.py
from django import forms
from .models import Mdfile, Share
from accounts.models import User
from django.core.exceptions import ValidationError

class CreateMdfileForm(forms.ModelForm):
    class Meta:
        model = Mdfile
        fields = ['title','base_text']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-title',
                'placeholder': 'ファイル名を入力'
            }),
            'base_text':  forms.Textarea(attrs={
                'id': 'auto-textarea',
                'class': 'form-base_text',
            })
        }
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # ← 必須
        super().__init__(*args, **kwargs)
    def clean_title(self):
        title = self.cleaned_data['title']
        if Mdfile.objects.filter(user=self.user, title=title).exists():
            if self.instance.pk:
                # 既存のインスタンスで、タイトルが変更されていない場合はエラーを出さない
                if self.instance.title == title:
                    return title
            raise ValidationError('このファイル名は既に使われています。')
        return title

class ShareForm(forms.ModelForm):
    class Meta:
        model = Share
        fields = ['to_user']
    # 'to_user' という名前のフィールドを定義
    to_user = forms.ModelChoiceField(
        queryset=User.objects.all().order_by("-created_at"), # データベースからすべてのユーザーを取得
        label="シェアするユーザー",    # フォームに表示されるラベル
        empty_label="ユーザーを選択してください", # 選択されていない場合のデフォルト表示
        # required=True, # デフォルトでTrue。選択必須にするなら明示的に書いても良い
    )

    def clean_to_user(self):
        to_user = self.cleaned_data['to_user']
        if (self.sharer == to_user):
            return ValidationError('自分は選択できません')
        return to_user

    def __init__(self, *args, **kwargs):
        # フォームを初期化する際に、自分自身（シェアする側）をquerysetから除外したい場合
        sharer = kwargs.pop('sharer', None)
        super().__init__(*args, **kwargs)
        self.sharer = sharer
        if sharer:
            # 現在のユーザーを除外したユーザーのクエリセットを設定
            self.fields['to_user'].queryset = User.objects.exclude(pk=sharer.pk)
        else:
            # sharer が提供されなかった場合は、すべてのユーザーを表示する（またはエラー処理）
            self.fields['to_user'].queryset = User.objects.all()

mdapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, ListView, CreateView, DetailView, UpdateView, DeleteView
from mdapp.models import Mdfile, Share
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from .services import converter, pdf_gerater, img_generater
from .forms import CreateMdfileForm, ShareForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse

# def index(request):
#     return render(request, 'mdapp/index.html')

img_strage_mode = "local"  # "s3" or "local"

class List(LoginRequiredMixin, ListView):
    model = Mdfile
    template_name = "mdapp/index.html"
    def get_queryset(self):
        return Mdfile.objects.filter(user=self.request.user).order_by("-created_at")
    # コンテキストを追加
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['share_form'] = ShareForm(sharer=self.request.user)
        return context

class Detail(LoginRequiredMixin, DeleteView):
    model = Mdfile
    template_name = "mdapp/detail.html"
    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404("存在しない記事です")
        return obj

class CreateFile(LoginRequiredMixin, CreateView):
    model = Mdfile
    form_class = CreateMdfileForm
    template_name = "mdapp/create.html"
    # success_url = reverse_lazy('mdapp:index')
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ここで user を渡す
        return kwargs
    def form_valid(self, form):
        self.object = form.save(commit=False)  # 明示的にobjectを更新
        self.object.user = self.request.user
        isinstance = form.instance
        isinstance.html_text = converter.markdown_to_html(isinstance.base_text)
        pdf_bytes = pdf_gerater.generater(isinstance.html_text)
        if img_strage_mode == "s3":
            print("S3に保存")
            isinstance.url = img_generater.generate_image_from_pdf(pdf_bytes, isinstance.title)
        elif img_strage_mode == "local":
            print("ローカルに保存")
            isinstance.url = img_generater.generate_image_from_pdf_local(pdf_bytes, isinstance.title, self.request.user.name)
        self.object.save()
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('mdapp:ditail', kwargs={'pk': self.object.id})

class UpdateFile(LoginRequiredMixin, UpdateView):
    model = Mdfile
    form_class = CreateMdfileForm
    template_name = "mdapp/create.html"
    # success_url = reverse_lazy('mdapp:index')
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ここで user を渡す
        return kwargs
    def form_valid(self, form):
        self.object = form.save()  # 明示的にobjectを更新
        self.object.user = self.request.user
        isinstance = form.instance
        isinstance.html_text = converter.markdown_to_html(isinstance.base_text)
        # imgを作成してS3に保存
        pdf_bytes = pdf_gerater.generater(isinstance.html_text)
        if img_strage_mode == "s3":
            print("S3に保存")
            isinstance.url = img_generater.generate_image_from_pdf(pdf_bytes, isinstance.title)
        elif img_strage_mode == "local":
            print("ローカルに保存")
            isinstance.url = img_generater.generate_image_from_pdf_local(pdf_bytes, isinstance.title, self.request.user.name)
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('mdapp:ditail', kwargs={'pk': self.object.id})
    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404("存在しない記事です")
        return obj

class Delet(LoginRequiredMixin, DeleteView):
    model = Mdfile
    template_name = "mdapp/detail.html"  # Getの際は詳細へ
    success_url = reverse_lazy('mdapp:index')
    def get_success_url(self):
        return reverse_lazy('mdapp:index')
    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk')
        referrer_url = self.request.META.get('HTTP_REFERER')
        if referrer_url:
            return HttpResponseRedirect(referrer_url)  # リクエストしてきたページ
        return HttpResponseRedirect(reverse_lazy('mdapp:ditail', kwargs={'pk': id}))  # 分からなければ詳細
    def get_object(self, queryset=None):
        obj = super().get_object(queryset)  
        if obj.user != self.request.user:
            raise Http404("存在しない記事です")
        return obj

@login_required
def get_pdf_bytedeta(request, pk):
    try:
        mdfile_instance = Mdfile.objects.get(pk=pk) 

        if mdfile_instance.user != request.user:
            raise Http404("存在しない記事です")

        html_text = mdfile_instance.html_text
        title = mdfile_instance.title
        pdf_bytes = pdf_gerater.generater(html_text)
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        # Content-Disposition ヘッダーを設定して、ダウンロード時のファイル名を指定
        # 'inline' にするとブラウザで直接開かれ、'attachment' にするとダウンロードダイアログが表示される
        # response['Content-Disposition'] = 'inline; filename="generated_report.pdf"'
        # ダウンロードさせる場合
        response['Content-Disposition'] = f"""attachment; filename="{title}.pdf" """
        return response
    except Mdfile.DoesNotExist:
        # 指定された pk の Mdfile が見つからない場合の処理
        return HttpResponse("指定された記事が見つかりませんでした。", status=404)
    except Exception as e:
        # その他の予期せぬエラー
        print(f"ビュー関数内でエラーが発生しました: {e}")
        return HttpResponse(f"エラーが発生しました: {e}", status=500)
    
@login_required
def generate_thumbnail(request, pk):
    try:
        mdfile_instance = Mdfile.objects.get(pk=pk)
        if mdfile_instance.user != request.user:
            raise Http404("存在しない記事です")
        html_text = mdfile_instance.html_text
        title = mdfile_instance.title
        pdf_bytes = pdf_gerater.generater(html_text)
        if img_strage_mode == "s3":
            print("S3に保存")
            isinstance.url = img_generater.generate_image_from_pdf(pdf_bytes, isinstance.title)
        elif img_strage_mode == "local":
            print("ローカルに保存")
            isinstance.url = img_generater.generate_image_from_pdf_local(pdf_bytes, isinstance.title, self.request.user.name)
        json_data = {
            'status': 'success',
            'message': 'サムネイル画像の生成に成功しました。',
            'img_url': img_url
        }
        return HttpResponse(json_data, content_type='application/json')
    except Mdfile.DoesNotExist:
        # 指定された pk の Mdfile が見つからない場合の処理
        return HttpResponse("指定された記事が見つかりませんでした。", status=404)
    except Exception as e:
        # その他の予期せぬエラー
        print(f"ビュー関数内でエラーが発生しました: {e}")
        return HttpResponse(f"エラーが発生しました: {e}", status=500)
    
@login_required
def get_img(request, filename):
    try:
        # 画像のパスを指定
        img_path = f"mdapp/static/mdapp/img/thumbs/{filename}"
        with open(img_path, 'rb') as img_file:
            response = HttpResponse(img_file.read(), content_type="image/jpeg")
            response['Content-Disposition'] = f'inline; filename="{filename}"'
            return response
    except FileNotFoundError:
        return HttpResponse("画像が見つかりませんでした。", status=404)

class Shared(LoginRequiredMixin, ListView):
    model = Share
    template_name = "mdapp/shared.html"
    def get_queryset(self):
        shared_files = Share.objects.filter(to_user=self.request.user).select_related("file", "file__user").order_by('created_at')
        files = []
        for f in shared_files:
            files.append({
                "shared_id": f.id,
                "file_id": f.file.id,
                "title": f.file.title,
                "base_text": f.file.base_text,
                "html_text": f.file.html_text,
                "url": f.file.url,
                "auther_user_id": f.file.user.id,
                "auther_user_name": f.file.user.name,
                "shared_at": f.created_at
            })
        return files

class CreateShared(CreateFile):
    model = Mdfile
    form_class = CreateMdfileForm
    template_name = "mdapp/create.html"
    # success_url = reverse_lazy('mdapp:index')
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # ここで user を渡す
        return kwargs
    def get_initial(self):
        share_id = self.kwargs.get('pk')
        try:
            share_instance= get_object_or_404(
                Share.objects.select_related('file', 'file__user'), 
                pk=share_id,
                to_user=self.request.user
            )
            initial = super().get_initial()
            initial["title"] = f"{share_instance.file.title}_by_{share_instance.file.user.name}"
            initial["base_text"] = share_instance.file.base_text
        except Exception as e:
            print(e)
        return initial

@login_required
@require_POST
def share(request, pk):
    mdfile = Mdfile.objects.get(pk=pk)
    if mdfile.user != request.user:
        raise Http404("存在しない記事です")
    print("テストテキスト",mdfile)
    print("テストテキスト",request.POST)
    form = ShareForm(request.POST, sharer=request.user)
    status_code = 200
    if form.is_valid():
        to_user = form.cleaned_data["to_user"]
        if not Share.objects.filter(file=mdfile, to_user=to_user).exists():
            Share.objects.create(
                file=mdfile,
                to_user=to_user
            )
            res_data = {"status": "success", "message": f"{to_user.name}にファイル[{mdfile.title}]を共有しました"}
        else:
            res_data = {"status": "info", "message": f"ファイル[{mdfile.title}]は{to_user.name}に既に共有済みです"}
    else:
        status_code = 400
        res_data = {"status": "error", "message": f"データが間違っています"}

mdapp/templates/mdapp/create.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'mdapp/css/index.css' %}" >
{% endblock %}

{% block content %}
<div class="md-container">
    <!-- <h1>ファイル作成画面</h1> -->
    
    <form method="post" class="create-md-form">
        {% csrf_token %}

        {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-danger">
                    {{ field.errors|striptags }}
                </div>
            {% endif %}
        {% endfor %}

        {{ form.title }}
        {{ form.base_text }}
        <!-- <input type="submit" value="🖋"> -->
        <div class="side-buttons side-button-submit" >
            <button type="submit" class="submit-button" style="">
                <i class="fa-solid fa-pen-to-square" style="font-size: 25px;"></i>
            </button>
        </div>
    </form>
</div>

<!-- <script>
    const textarea = document.getElementById('auto-textarea');
    // function autoResize(el) {
    //     el.style.height = 'auto';
    //     el.style.height = el.scrollHeight + 'px';
    // }
    function autoResize(el) {
        const scrollY = window.scrollY; // 現在のスクロール位置を記録
        console.log("0:", scrollY);
        requestAnimationFrame(() => {
            el.style.height = 'auto';
            el.style.height = el.scrollHeight + 'px';
            window.scrollTo({ top: scrollY }); // 
        });
        const scrolY = window.scrollY; // 現在のスクロール位置を記録
        console.log("1:",scrolY);
    }
    // 入力時
    textarea.addEventListener('input', () => autoResize(textarea));
    // ページ読み込み時にも実行
    window.addEventListener('DOMContentLoaded', () => autoResize(textarea));
</script> -->

{% endblock %}

mdapp/templates/mdapp/detail.html
{% extends "base.html" %}
<!-- {% load static %} -->

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'mdapp/css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'mdapp/css/mdfile.css' %}" >
{% endblock %}

{% block content %}

<div class="md-container">
    <div class="flex-container" style="margin-bottom: 5px;">
        <div style="font-size: xx-large;">{{ object.title }}</div>
    </div>

    <div class="html-fild">
        <div class="html-fild_text">
            {{ object.html_text|safe }}
        </div>
    </div>
<!-- 
    <div>
        <a href="/files/{{ object.id }}/img">img生成</a>
    </div> -->

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">注意！</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ object.title }}を削除して大丈夫ですか？<br>  
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
                    <form action="/files/{{object.id}}/delete" method="post">
                        {% csrf_token %}
                        <!-- <button type="submit">
                            <i class="fa-solid fa-trash"></i>
                        </button> -->
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="btn-group-vertical side-buttons" role="group" aria-label="Vertical button group">
        <!-- <button type="button" class="btn btn-primary">Button</button>
        <button type="button" class="btn btn-primary">Button</button>
        <button type="button" class="btn btn-primary">Button</button> -->
        <form method="get" action="/files/{{object.id}}/pdf" style="width: 100%;">
            <button type="submit" class="btn btn-secondary col-button" >
                <i class="fa-solid fa-file-arrow-down"></i>
            </button>
        </form>
        <form method="get" action="/files/{{ object.id }}/update" style="width: 100%;">
            <button type="submit" class="btn btn-secondary col-button">
                <i class="fa-solid fa-pen-to-square"></i>
            </button>
        </form>
        <button type="button" class="btn btn-danger col-button" data-bs-toggle="modal" data-bs-target="#exampleModal" >
            <i class="fa-solid fa-trash"></i>
        </button>
    </div>

</div>

{% endblock %}

mdapp/templates/mdapp/index.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'mdapp/css/index.css' %}" >
{% endblock %}

{% block content %}

<!-- <h1>とりまホーム画面</h1> -->
<div class="" style="display: flex; justify-content: center;">
    <div class="center-block" style="max-width: 800px; margin-left: 50px; margin-right: 50px;">
        <div class="row row-cols-2 row-cols-md-3 g-4">
            {% if object_list %}
                {% for item in object_list %}
                    <div class="col">
                        <div class="card h-60">
                            <a href="/files/{{item.id}}">
                                {% if item.url %}
                                    <img src="{{ item.url }}" class="card-img-top" alt="..." onerror="this.onerror=null; this.src=`{% static 'mdapp/img/NoIMG.jpg' %}`;">
                                {% else %}
                                <img src="{% static 'mdapp/img/NoIMG.jpg' %}" class="card-img-top" alt="...">
                                {% endif %}
                            </a>
                            <div class="card-body card-body-css" style="display: flex; justify-content: space-between; align-items: center; background-color: rgb(240, 240, 240);">
                                <a href="/files/{{item.id}}">
                                    <h5 class="card-title">{{ item.title }}</h5>
                                </a>
                                <!-- <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p> -->
                                <div class="dropdown stopEventChild" style="">
                                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="/files/{{item.id}}/pdf">PDFとして保存</a></li>
                                        <li><a class="dropdown-item" href="/files/{{ item.id }}/update">編集</a></li>
                                        <div class="btn-group dropend">
                                            <button id="" type="button" class="dropdown-toggle share-togle-index" data-bs-toggle="dropdown" aria-expanded="false">
                                                共有
                                            </button>
                                            <ul class="dropdown-menu">
                                                <form id="share-form-{{ item.id }}" method="post" action="{% url 'mdapp:share' pk=item.id %}">
                                                    {% csrf_token %}
                                                    {{ share_form.as_p }}
                                                    <input type="submit">
                                                </form>
                                            </ul>
                                        </div>
                                        <li style=""><button type="button" class="" data-bs-toggle="modal" data-bs-target="#indexDeleteModal" item-title="{{ item.title }}" item-id="{{ item.id }}"  style="border: none; background: none; padding: 0;">
                                            <a class="dropdown-item" href="#">削除</a>
                                        </button></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <!-- Modal -->
                    <div class="modal fade" id="indexDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">注意！</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <span id="modalDeleteItemTitle"></span>を削除して大丈夫ですか？<br>  
                                </div>
                                <div class="modal-footer">
                                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
                                    <form id="deleteForm" method="post">
                                        {% csrf_token %}
                                        <!-- <button type="submit">
                                            <i class="fa-solid fa-trash"></i>
                                        </button> -->
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
            {% else %}
                    <h4 style="width: 300px;">右下からノートを追加！</h4>
            {% endif %}        
        </div>
    </div>
    <form action="/create" style="position: fixed; bottom: 60px; right: 70px;">
        <button type="submit" class="edit-button" style="">
            <i class="fa-solid fa-pen edit-button-pen" style="font-size: 25px;"></i>
        </button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // 該当要素が複数あるのでforcachですべてにイベントをつける
        const buttons = document.getElementsByClassName('stopEventChild');
        Array.from(buttons).forEach(function(button) {
            button.addEventListener('click', function(event) {
                // 親要素へのイベント伝播を停止
                event.stopPropagation();
            });
        });

        // formに非同期イベントを実装
        document.querySelectorAll("form[id^='share-form-']").forEach(form => {
            form.addEventListener("submit", async function(event) {
                event.preventDefault(); // submit停止
                const formData = new FormData(this);
                try {
                    const res = await fetch(this.action, {
                        method: "POST",
                        headers: {
                            "X-Requested-With": "XMLHttpRequest",
                            "X-CSRFToken": formData.get("csrfmiddlewaretoken"), // hidden inputからCSRFトークンを取得　できるらしい
                        },
                        body: formData
                    });
                    const data = await res.json();
                    console.log(data)
                    if (res.ok) {
                        alert(data["message"])
                    } else {
                        alert('シェアできませんでした')
                    }
                } catch (e) {
                    console.error(e)
                    alert('error')
                }
            });
        });
    });
</script>

{% endblock %}

mdapp/templates/mdapp/plane.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
{% endblock %}

{% block content %}

<h1>画面</h1>

{% endblock %}

mdapp/templates/mdapp/shared.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
{% endblock %}

{% block content %}

<div>
    <div class="" style="display: flex; justify-content: center;">
        <div class="center-block" style="max-width: 800px; margin-left: 50px; margin-right: 50px;">

            <h1>共有されているファイル</h1>

            <div class="row row-cols-2 row-cols-md-3 g-4">
                {% if object_list %}
                    {% for item in object_list %}
                        <div class="col">
                            <div class="card h-60">
                                <a href="{% url 'mdapp:create_shared' pk=item.shared_id %}">
                                    {% if item.url %}
                                        <img src="{{ item.url }}" class="card-img-top" alt="...">
                                    {% else %}
                                    <img src="{% static 'mdapp/img/NoIMG.jpg' %}" class="card-img-top" alt="...">
                                    {% endif %}
                                </a>
                                <div class="card-body card-body-css" style="background-color: rgb(240, 240, 240);">
                                    <a href="{% url 'mdapp:create_shared' pk=item.shared_id %}">
                                        <h5 class="card-title">{{ item.title }}</h5>
                                    </a>
                                    <!-- <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p> -->
                                    <p>作成者:{{item.auther_user_name}}</p>
                                    <p>{{item.shared_at|date:"H:i Y/m/d"}}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                {% else %}
                        <h4 style="width: 300px;">共有されたファイルはありません</h4>
                {% endif %}        
            </div>
        </div>
    </div>

    <!-- <div>
        {% if object_list %}
        {% for item in object_list %}
            <div>
                <a href="{% url 'mdapp:create_shared' pk=item.shared_id %}">{{item.title}}</a>
            </div>
        {% endfor %}
        {% endif %}
    </div> -->
</div>

{% endblock %}